---
title: "Publications"
editor: visual
---


::: {.callout-note}
## Links

>- **Google Scholar**: <https://ac.scmor.com/>
>- **ORCID**: <https://orcid.org/my-orcid?orcid=0009-0004-8447-6491>
>- **ResearchGate:** <https://www.researchgate.net/>
:::

&emsp;

## 期刊论文

-   Hou H, Zhang J, Huang S, et al. Mechanical effect of taper position in abutment hole and screw taper angles on implant system and peri-implant tissue: a finite element analysis[J]. Computer Methods in Biomechanics and Biomedical Engineering, 2024: 1-9.[-Link-](https://www.tandfonline.com/doi/abs/10.1080/10255842.2024.2423253)
-   Zhang J(advisor), Hou H, Chen P, et al. Mechanical and modal analysis of different implant strategies for loss of three teeth with bone atrophy in the maxillary posterior region[J]. Computer Methods in Biomechanics and Biomedical Engineering, 2024: 1-10.[-Link-](https://www.tandfonline.com/doi/abs/10.1080/10255842.2024.2358363)
-   Zhang J(advisor), Hou H, Chen P, et al. Biomechanical Performance of Different Implant Spacings and Placement Angles in Partial Fixed Denture Prosthesis Restorations: A Finite Element Analysis[J]. Journal of Medical and Biological Engineering, 2024, 44(5): 685-695.[-Link-](https://www.tandfonline.com/doi/abs/10.1080/10255842.2024.2358363)
-   Zhang J, Lin M, Hou H, et al. EASAM: an edge-aware SAM-based paradigm for tooth segmentation[J]. Signal, Image and Video Processing, 2025, 19(8): 673.[-Link-](https://link.springer.com/article/10.1007/s11760-025-04208-2)

## 科研项目

1. 上海市“科技创新行动计划”自然科学基金面上项目（编号：23141901400），2022-2023. 参与，已结项
2. 上海应用技术大学协同创新基金-跨学科、多领域合作研究专项（编号：XTCX2023-18）， 2023-2024. 参与，已结项
